service:
  name: EdgeService
  host: 10.252.67.252
  tags:
    - edge
    - FlowFederate
    - service

consul:
  host: 127.0.0.1
  port: 8500

rabbitmq:
  host: 127.0.0.1
  port: 5672

mysql:
  host: 127.0.0.1
  port: 3306
  database: FlowFederate
  user: wxy
  password: 123456

client:
  name: ClientService

debug: true