service:
  name: EdgeService
  tags:
    - edge
    - FlowFederate
    - service

consul:
  host: consul
  port: 8500

rabbitmq:
  host: rabbitmq
  port: 5672

mysql:
  host: mysql
  port: 3306
  database: FlowFederate
  user: FlowFederate
  password: 123456

client:
  name: ClientService

common_name: FlowFederate