# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: edge.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nedge.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n\x0cTrainRequest\x12\x0c\n\x04\x63onf\x18\x01 \x01(\t2D\n\x0b\x45\x64geService\x12\x35\n\tTrainTask\x12\x10.pb.TrainRequest\x1a\x16.google.protobuf.EmptyB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edge_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_TRAINREQUEST']._serialized_start=47
  _globals['_TRAINREQUEST']._serialized_end=75
  _globals['_EDGESERVICE']._serialized_start=77
  _globals['_EDGESERVICE']._serialized_end=145
# @@protoc_insertion_point(module_scope)
