service:
  name: ClientService
  tags:
    - client
    - FlowFederate
    - service

consul:
  host: consul
  port: 8500

mysql:
  host: mysql
  port: 3306
  database: FlowFederate
  user: FlowFederate
  password: 123456

debug: true