service:
  name: ClientService
  host: 113.54.234.76
  tags:
    - client
    - FlowFederate
    - service

consul:
  host: 127.0.0.1
  port: 8500

mysql:
  host: 127.0.0.1
  port: 3306
  database: FlowFederate
  user: wxy
  password: 123456

debug: true