api:
  name: FlowFederate-Api
  tags:
    - api
    - FlowFederate

service:
  edge: EdgeService

consul:
  host: consul
  port: 8500

mysql:
  host: mysql
  port: 3306
  database: FlowFederate
  user: FlowFederate
  password: 123456

debug: true