api:
  name: FlowFederate-Api
  host: 113.54.234.76
  tags:
    - api
    - FlowFederate

service:
  edge: EdgeService

consul:
  host: 127.0.0.1
  port: 8500

mysql:
  host: 127.0.0.1
  port: 3306
  database: FlowFederate
  user: wxy
  password: 123456

debug: true